#!/usr/bin/env bash
#while case
i=1
while [ $i -lt 21 ]
do
  	echo $i
	case $i in 
	4) 
		echo "bad luck from China"
	;;
	9)
		echo "bad luck from Japan";;
	17)
		echo "bad luck from Italy"
	esac

	#echo "Holberton School"
	((i++)) 
done

