#!/usr/bin/env bash
#The content of the current directory In a list format
# only the part of the name after the first dash is displayed

list=$(ls)
for i in $list; do
 echo "$i" | cut -d '-' -f2
done
